__all__ = [
    "ENTRY_SCHEMA_VERSION",
    "DID_METHOD_SPEC_VERSION",
    "DID_METHOD_NAME",
    "ENTRY_SIZE_LIMIT",
]

ENTRY_SCHEMA_VERSION = "1.0.0"
DID_METHOD_NAME = "did:factom"
DID_METHOD_SPEC_VERSION = "0.2.0"
ENTRY_SIZE_LIMIT = 10275
