__all__ = [
    "ENTRY_SCHEMA_V100",
    "DID_METHOD_SPEC_V020",
    "DID_METHOD_NAME",
    "ENTRY_SIZE_LIMIT",
]

ENTRY_SCHEMA_V100 = "1.0.0"
DID_METHOD_NAME = "did:factom"
DID_METHOD_SPEC_V020 = "0.2.0"
ENTRY_SIZE_LIMIT = 10275
