language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
  dist: xenial
  sudo: true
install:
- pip install pipenv
- pipenv install -d --pre
script:
- pytest --cov=./factom_did/client/ --cov=./factom_did/resolver
after_success:
- coveralls
